modLoader="javafml"
loaderVersion="[4,)" # NeoForge 21.1.x
license="${mod_license}"
issueTrackerURL=""

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''
Unify ores, raw drops, ingots/gems, and compression tiers across mods. Data-driven, tag-first.
'''

[[dependencies.${mod_id}]]
   modId="neoforge"
   type="required"
   versionRange="[21.1.0,)"
   ordering="NONE"
   side="BOTH"
