[general]
enableDropUnifier = true # global loot modifier for canonical ore drops

[compression]
enable = true
enableMetals = true
enableGems = true
enableStones = true
maxTier = 9

[filters]
# Unified materials to deny at bootstrap time (metals or gems)
denyMaterials = []
# Stones to deny at bootstrap time
denyStones = []
